feat: Add codable identifier arrays
IBM-Swift/SafetyContracts pull request #15
Opened 2018-02-26 11:30 UTC by Andrew-Lees11

Added type Aliases and docs for returning an array of tuples of identifiers to codable object. 

This is needed for the corresponding [pull request](https://github.com/IBM-Swift/Kitura/pulls) in Kitura

Has been tested with swift test and everything passed.

2018-02-26 13:29 UTC, ianpartridge requested changes

2018-02-26 13:29 UTC, ianpartridge commented on Sources/KituraContracts/ClosureAliases.swift
> + The `IdentifierCodableArrayResultClosure` is used by other `Codable` aliases when responding with an array of tuples containing an identifiers and a Codable object, or an `RequestError`.
s/identifiers/identifier

2018-02-26 13:29 UTC, ianpartridge commented on Sources/KituraContracts/ClosureAliases.swift
> + The `IdentifierCodableArrayClosure` is for use in cases where you'd want to perform a series of actions then respond with an array of tuples containing an identifiers and a Codable object, or an `Re
s/identifiers/identifier

2018-02-28 10:09 UTC, Andrew-Lees11 commented
@ianpartridge Have made identifiers identifier as requested.

2018-03-03 05:34 UTC, seabaylea approved these changes
LGTM

2018-03-03 05:37 UTC, ianpartridge approved these changes

2018-03-03 05:40 UTC, merged

2018-03-03 05:40 UTC, ianpartridge commented
Thanks @Andrew-Lees11 - this will need tagging so it can be used from your Kitura PR.  I haven't done that.

2018-03-20 16:21 UTC, djones6 commented
This is tagged in `0.0.20`.