fixed compiler warnings generated by swift 5.3. Still works with 5.1
IBM-Swift/SafetyContracts pull request #57
Opened 2020-11-01 00:46 UTC by mlilback

When compiled with swift 5.3, a number of warnings like this are generated:

```
/home/mlilback/rc2/KituraContracts/Sources/KituraContracts/Contracts.swift:1437:15: warning: immutable property will not be decoded because it is declared with an initial value which cannot be overwritten
  private let `operator`: Operator = .inclusiveRange
```
This change fixes these warnings, and is compatible with swift 5.1.

2020-11-01 00:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kitura/KituraContracts?pullRequest=57) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kitura/KituraContracts?pullRequest=57) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kitura/KituraContracts?pullRequest=57) it.</sub>

2020-11-02 06:36 UTC, mbarnach commented
Hi @mlilback, Any idea for the reason for the warning (ie. compiler change for which reason)?

2020-11-02 17:15 UTC, mlilback commented
The person who made the change explains it [here](https://stackoverflow.com/questions/62545594/xcode-warning-immutable-property-will-not-be-decoded-because-it-is-declared-wit) Apparently it was the cause of a lot of bugs. It makes sense to me, as you can only assign to a let once, and the synthesized Decodable init has to read everything from the serialized data.

2020-11-02 23:53 UTC, dannys42 commented
@mlilback Sounds good.  Are you able to sign the CLA?

2020-11-03 07:45 UTC, mbarnach requested changes
Thanks for the link @mlilback! That's very interesting indeed!

I think we should rather go for the exclusion option (option 3).
Otherwise, you can decode, eg. a `greaterThan` operator with the `lowerThan` operation inside. I think it makes more sense also, as why would you serialise the operator explicitly in such operation?

2020-11-10 23:55 UTC, mlilback commented
Option 3 doesn't work. Adding CodingKeys gives the error 

```2. Cannot automatically synthesize 'Decodable' because 'value' does not have a matching CodingKey and does not have a default value```

Creating an empty `init(from decoder: Decoder)`  gives the error

```Return from initializer without initializing all stored properties```

I kept experimenting and didn't find a solution. You can't manually set it in the init method, as it is a value not known to that method.

Option 2 will work, since all properties are private they can all be vars.

Should I switch to option 2?

2020-11-11 07:57 UTC, mbarnach commented
Option 3 should be with default value and no coding key for it. This is not compiling? Strange. I will have a look at it. Thanks for reporting.

2020-11-11 08:15 UTC, mbarnach commented
@mlilback I've made an alternate PR (#58 ) so we can see the difference in the implementation.

2020-11-15 16:45 UTC, mkll commented
Guys, are you sure that these structs should be Decodable ever? It seems that only Encodable makes sense to them. Looks like this var gives meaning to the corresponding struct. It should never change. Or am I missing something?

2021-02-27 01:24 UTC, dannys42 commented
Closing this since PR 58 appears to resolve the issue.

2021-02-27 01:24 UTC, closed without merging